#!/usr/bin/env python3
"""
03_27nt_exact_genome_scan.py

Count exact genome-wide matches of a peptide-coding 27-nt sequence against hg38.
Both the query sequence and its reverse complement are scanned across all contigs
listed in the samtools FASTA index (.fai).

Intended use: Hulen et al. 2026 availability/reproducibility repository.

Requirements:
  - Python 3
  - PyYAML
  - samtools available in PATH
  - indexed hg38 FASTA (<hg38.fa>.fai)

Usage:
  python3 code/03_27nt_exact_genome_scan.py --config config/config.yaml

By default, this expects the query FASTA generated by
02_EVA003_peptide_repeat_context.sh:
  <outdir>/<peptide>_27nt.fa
"""

from __future__ import annotations

import argparse
import subprocess
from pathlib import Path

import yaml


def reverse_complement(dna: str) -> str:
    table = str.maketrans("ACGTNacgtn", "TGCANtgcan")
    return dna.translate(table)[::-1].upper()


def count_overlapping(haystack: str, needle: str) -> int:
    count = 0
    start = 0
    while True:
        idx = haystack.find(needle, start)
        if idx == -1:
            return count
        count += 1
        start = idx + 1


def read_single_fasta_sequence(path: Path) -> str:
    if not path.exists():
        raise FileNotFoundError(f"Query FASTA not found: {path}")
    seq = []
    with path.open("r", encoding="utf-8") as handle:
        for line in handle:
            line = line.strip()
            if not line or line.startswith(">"):
                continue
            seq.append(line.upper())
    dna = "".join(seq)
    if not dna:
        raise ValueError(f"No sequence found in FASTA: {path}")
    return dna


def fetch_contig(reference_fasta: Path, contig: str) -> str:
    result = subprocess.run(
        ["samtools", "faidx", str(reference_fasta), contig],
        check=True,
        text=True,
        capture_output=True,
    )
    return "".join(result.stdout.splitlines()[1:]).upper()


def main() -> None:
    parser = argparse.ArgumentParser(description="Count exact genome-wide matches of a 27-nt query sequence.")
    parser.add_argument("--config", required=True, help="Path to config.yaml")
    parser.add_argument("--query-fasta", default=None, help="Optional query FASTA override")
    parser.add_argument("--output", default=None, help="Optional output file override")
    args = parser.parse_args()

    with open(args.config, "r", encoding="utf-8") as handle:
        cfg = yaml.safe_load(handle)

    outdir = Path(cfg["outputs"]["outdir"])
    reference_fasta = Path(cfg["references"]["hg38_fasta"])
    peptide = cfg["targets"]["peptide"]

    query_fasta = Path(args.query_fasta) if args.query_fasta else outdir / f"{peptide}_27nt.fa"
    output_path = Path(args.output) if args.output else outdir / f"{peptide}_27nt_genomewide_exact_match_summary.txt"

    if not reference_fasta.exists():
        raise SystemExit(f"ERROR: Reference FASTA not found: {reference_fasta}")
    fai = Path(str(reference_fasta) + ".fai")
    if not fai.exists():
        raise SystemExit(f"ERROR: Reference FASTA index not found: {fai}. Run: samtools faidx {reference_fasta}")

    query = read_single_fasta_sequence(query_fasta).upper()
    if len(query) != 27:
        raise SystemExit(f"ERROR: Query length is {len(query)} nt; expected 27 nt.")

    revcomp = reverse_complement(query)
    contigs = [line.split("\t")[0] for line in fai.open("r", encoding="utf-8")]

    total_forward = 0
    total_reverse_complement = 0
    per_contig_hits = []

    for contig in contigs:
        sequence = fetch_contig(reference_fasta, contig)
        forward_count = count_overlapping(sequence, query)
        reverse_count = count_overlapping(sequence, revcomp)
        if forward_count or reverse_count:
            per_contig_hits.append((contig, forward_count, reverse_count))
        total_forward += forward_count
        total_reverse_complement += reverse_count

    output_path.parent.mkdir(parents=True, exist_ok=True)
    with output_path.open("w", encoding="utf-8") as out:
        out.write(f"Query_27nt\t{query}\n")
        out.write(f"Query_27nt_reverse_complement\t{revcomp}\n")
        out.write(f"Total_exact_matches_forward\t{total_forward}\n")
        out.write(f"Total_exact_matches_reverse_complement\t{total_reverse_complement}\n")
        out.write(f"Total_exact_matches_either_strand\t{total_forward + total_reverse_complement}\n")
        out.write("\nContig\tForward_matches\tReverse_complement_matches\n")
        for contig, forward_count, reverse_count in per_contig_hits:
            out.write(f"{contig}\t{forward_count}\t{reverse_count}\n")

    print(f"Wrote: {output_path}")


if __name__ == "__main__":
    main()
